### DISCUSSION TITLE
How write logs to file with unicorn config

### DISCUSSION THREAD

**Discussion by ahvahsky2008** [Kludex/uvicorn#1450] [Q&A]
Its my uvicorn log_config.yaml. All works perfect untill i add logging to file. Its says to me

`ValueError: not enough values to unpack (expected 5, got 0)`
I try different variations of logging (FileHandler,RotateHandler) but same issue raised.

```
version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: "[%(asctime)s %(process)d:%(threadName)s] %(name)s - %(levelname)s - %(message)s | %(filename)s:%(lineno)d"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr

  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: access
    filename: info.log
    encoding: utf8
    mode: a

loggers:
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: no
```
