### DISCUSSION TITLE
When --log-config is supplied, exception traceback does not show root cause exception

### DISCUSSION THREAD

**Discussion by yunduz** [Kludex/uvicorn#2227] [Potential Issue]
Hello,

When I run uvicorn (with FastAPI) where I supply `--log-config logging.yaml` argument, when an exception is raised, full stack trace is not shown (only the topmost exception and its traceback). However, if I don't supply log config file, then full stack trace down to the original exception is shown.

I debugged it down to [this line](https://github.com/encode/uvicorn/blob/master/uvicorn/middleware/message_logger.py#L84) in the `uvicorn` code: `raise exc from None`. If I remove `from None`, full stack trace is shown even when `--log-config` is supplied.
Wondering if it's intentional to clear the original exception?

To reproduce the issue, create the following two files:

```python
# app.py

from fastapi import FastAPI

app = FastAPI()


def foo():
    try:
        raise ValueError("blah 1")
    except Exception as e:
        raise ValueError("blah 2") from e


def bar():
    try:
        foo()
    except Exception as e:
        raise ValueError("blah 3") from e


@app.get("/foobar")
def foo_bar():
    bar()
```

```yaml
# logging.yaml
version: 1
disable_existing_loggers: False
formatters:
  simple:
    # designed to match loguru format
    format: "FROMPYTHONLOGGER%(asctime)s | %(levelname)-8s | %(process)-6s | %(name)s:%(funcName)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

loggers:
  service:
    level: INFO

root:
  level: INFO
  handlers: [console]
```

Run the app:
`uvicorn app:app --port 8201 --reload --log-config logging.yaml`
Make request to `localhost:8201/foobar`, observe logs: you'll see that only topmost `ValueError` with `blah 3` is shown in the logs.
