### DISCUSSION TITLE
No logs after uvicorn starts

### DISCUSSION THREAD

**Discussion by sonic-needlemouse** [Kludex/uvicorn#2245] [Q&A]
After I start my uvicorn application with the command `uvicorn dcb_record_linker.server:app --host 127.0.0.1 --port 4372` I don't observe  logs at all. There are only 2 messages in the logs:

/home/xxxxxx/lib/python3.9/site-packages/dask/dataframe/_pyarrow_compat.py:23: UserWarning: You are using pyarrow version 11.0.0 which is known to be insecure. See https://www.cve.org/CVERecord?id=CVE-2023-47248 for further details. Please upgrade to pyarrow>=14.0.1 or install pyarrow-hotfix to patch your current version.
  warnings.warn(
2024-02-07T12:47:07.722Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (65) - Fetching model from dvc. 

Tried this commands:
`uvicorn dcb_record_linker.server:app --host 127.0.0.1 --port 4372 `
`uvicorn dcb_record_linker.server:app --host 127.0.0.1 --port 4372 --log-level critical`
`uvicorn dcb_record_linker.server:app --host 127.0.0.1 --port 4372 --log-level info`

And I tried different ports, but the result was always the same.

Log config: 
```
version: 1
disable_existing_loggers: False
root: # configuration if no logger like is set: logger = logging.getLogger()
  level: INFO
  handlers: [dcb_console_handler, dcb_rotating_file_handler]
loggers:
  dcb_root_logger: # default logger for dcb packages
    level: INFO
    handlers: [dcb_console_handler, dcb_rotating_file_handler]
    propagate: False
formatters:
  dcb_simple_formatter:
    class: logging.Formatter
    format: "%(asctime)s.%(msecs)03dZ dcb_record_linker [%(threadName)s] %(levelname)s %(filename)s:%(funcName)s (%(lineno)d) - %(message)s\n"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  dcb_rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: dcb_simple_formatter
    filename: app.log
    mode: "a"
    # append mode
    maxBytes: 10485760
    # 100 MB
    backupCount: 3
    # maximum number of backups example: app.log.1 - 3
    encoding: "utf8"
    delay: False
  dcb_console_handler:
    # redirects all logging events to the console (sys.stdout)
    class: logging.StreamHandler
    level: INFO
    formatter: dcb_simple_formatter
    stream: ext://sys.stdout
```
