### DISCUSSION TITLE
Startup info logs missing from uvicorn after the launch of the app

### DISCUSSION THREAD

**Discussion by sonic-needlemouse** [Kludex/uvicorn#2247] [Potential Issue]
After the command `uvicorn dcb_record_linker.server:app --host 127.0.0.1 --port 4372` I observe this output in logs:

/home/xxxx/yes/envs/reli/lib/python3.9/site-packages/dask/dataframe/_pyarrow_compat.py:23: UserWarning: You are using pyarrow version 11.0.0 which is known to be insecure. See https://www.cve.org/CVERecord?id=CVE-2023-47248 for further details. Please upgrade to pyarrow>=14.0.1 or install pyarrow-hotfix to patch your current version.
  warnings.warn(
2024-02-08T12:49:49.760Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (65) - Fetching model from dvc.
2024-02-08T12:49:49.871Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (71) - Size of model directory: 8.19 MB                                                                                                                                                                                                                                
2024-02-08T12:49:49.871Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (72) - Model successfully pulled from dvc.

**But I expect these messages (start up information) in logs:**

/home/xxxx/yes/envs/reli/lib/python3.9/site-packages/dask/dataframe/_pyarrow_compat.py:23: UserWarning: You are using pyarrow version 11.0.0 which is known to be insecure. See https://www.cve.org/CVERecord?id=CVE-2023-47248 for further details. Please upgrade to pyarrow>=14.0.1 or install pyarrow-hotfix to patch your current version.
  warnings.warn(
2024-02-08T12:49:49.760Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (65) - Fetching model from dvc.
2024-02-08T12:49:49.871Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (71) - Size of model directory: 8.19 MB                                                                                                                                                                                                                                      
2024-02-08T12:49:49.871Z dcb_record_linker [MainThread] INFO server.py:_load_model_from_dvc (72) - Model successfully pulled from dvc.
NFO:     Uvicorn running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
INFO:     Started reloader process [34318] using StatReload
INFO:     Started server process [34320]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

At the same time, if I go to the host:port/docs page and send requests in the logs, I see info logs from uvicorn:

INFO:     127.0.0.1:60778 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:60778 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:60778 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:60778 - "GET /openapi.json HTTP/1.1" 200 OK

This is my config file: 
```
version: 1
disable_existing_loggers: False
root: # configuration if no logger like is set: logger = logging.getLogger()
  level: CRITICAL
  handlers: [dcb_console_handler, dcb_rotating_file_handler]
loggers:
  dcb_root_logger: # default logger for dcb packages
    level: INFO
    handlers: [dcb_console_handler, dcb_rotating_file_handler]
    propagate: False
formatters:
  dcb_simple_formatter:
    class: logging.Formatter
    format: "%(asctime)s.%(msecs)03dZ dcb_record_linker [%(threadName)s] %(levelname)s %(filename)s:%(funcName)s (%(lineno)d) - %(message)s\n"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  dcb_rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: dcb_simple_formatter
    filename: app.log
    mode: "a"
    # append mode
    maxBytes: 10485760
    # 100 MB
    backupCount: 3
    # maximum number of backups example: app.log.1 - 3
    encoding: "utf8"
    delay: False
  dcb_console_handler:
    # redirects all logging events to the console (sys.stdout)
    class: logging.StreamHandler
    level: NOTSET
    formatter: dcb_simple_formatter
    stream: ext://sys.stdout
```
