### DISCUSSION TITLE
How do I use --log-config for uvicorn and my apps logging?

### DISCUSSION THREAD

**Discussion by ChrisDAT20** [Kludex/uvicorn#2460] [Q&A]
I do not want to introduce my own approach on how to configure loggers. As uvicorn provides a possibility to configure logging via --log-config, I want to define all loggers there. Within my app, I use logging.info(...) and occasionally logging.getLogger(loggerName). So most of the time the log messages should go to the root logger. 
But thats not the case. uvicorns log messages are routed according to the log cfg specified via --log-config, but the other log messages arrive nowhere.
Why is the root logger not used when logging with "logging.info(...)"?

```
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(filename)s:%(lineno)d | %(levelname)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console]
  propagate: no
```
