### DISCUSSION TITLE
Some info-level logs are omitted when using a custom log config

### DISCUSSION THREAD

**Discussion by jm-alan** [Kludex/uvicorn#2505] [Potential Issue]
Normally, when starting uvicorn via the CLI
```bash
uvicorn main:app --workers 1 --port 8000 --reload
```
Some helpful startup information is printed to stdout:
```
INFO:     Started server process [78387]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```
It also includes WebSocket connection info, which is particularly useful for my application, as it is heavily SSE-dependent
```
INFO:     ('127.0.0.1', 49607) - "WebSocket /gM7LC56AaxtzEiNUx-b6d/" [accepted]
INFO:     connection open
< ... time passes ... >
INFO:     connection closed
```
However, when configured with a custom formatter, this startup and WebSocket connection info goes away, and only typical HTTP requests appear in the logs, even with the log level set to DEBUG
```yaml
version: 1
formatters:
  level-green:
    format: "%(levelname)s - %(name)s - %(asctime)s - %(message)s"
handlers:
  stdout-debug:
    level: DEBUG
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: level-green
root:
  level: DEBUG
  handlers:
    [stdout-debug]
```

I see all of my application's DEBUG logging, along with those from its dependencies, but the startup information, and runtime websocket connection info, is gone.
