### ISSUE TITLE
Question : patching uvicorn.access logger format

### ISSUE THREAD

**Issue by 0xAcid** [Kludex/uvicorn#638]
Hey guys, not sure if this is supposed to be doable easily, but I tried multiple things, and could not manage to do it properly.
Currently when a route is accessed through uvicorn, i have a log of it :
```
INFO:     127.0.0.115380 - "GET / HTTP/1.1" 200 OK
```

I would like to add the timestamp of the access to the log, but despite many tries patching the uvicorn.access logger, i could not manage to get it working. (i'm pretty sure the answer is out somewhere, but I've been trying stuff without success..)

**Comment by euri10** [comment]
in order to do that you can use the `log_config` kwarg and pass a dict that sets a formatter for the `uvicorn.access` logger with the timestamp you'd like to print.
Look at https://docs.python.org/3/library/logging.html?highlight=formatter#logrecord-attributes for the attibutes you may use, asctime looks like a good candidate.

you'd therefore run uvicorn this way:
`    uvicorn.run(
        "manage:app",
        host="0.0.0.0",
        log_config=log_config,
    )
`
and log_config would be the dict equivalent of this yaml:


```yaml
version: 1
disable_existing_loggers: False
formatters:
  uvicorn_access:
    "()": "uvicorn.logging.AccessFormatter"
    fmt: "%(levelprefix)s %(asctime)s %(client_addr)s - '%(request_line)s' %(status_code)s"
    use_colors: True
handlers:
  uvicorn_access:
    formatter: uvicorn_access
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
loggers:
  uvicorn.error:
    level: DEBUG
    handlers: [uvicorn_default]
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers: [uvicorn_access]
    propagate: no
```

and that would print
```
INFO:     2020-04-23 14:13:37,715 127.0.0.1:37856 - 'GET / HTTP/1.1' 404 Not Found
```
